# Generated by Django 3.2.22 on 2023-10-10 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consola', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direccion del Articulo')),
                ('link1', models.CharField(default='no_hay_nada', max_length=30)),
                ('sinopsis', models.TextField()),
                ('image', models.ImageField(default='img_avatar1.png', upload_to='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
